{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "node-graphql-chart.postgresFullname" . }}
  labels:
    {{- include "node-graphql-chart.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "node-graphql-chart.postgresFullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "node-graphql-chart.postgresFullname" . | quote }}
  template:
    metadata:
      labels:
        app: {{ include "node-graphql-chart.postgresFullname" . | quote }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image | quote }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
              name: postgres
          env:
            - name: PGDATA
              value: {{ .Values.postgres.dataDir | quote }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "node-graphql-chart.postgresFullname" . }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "node-graphql-chart.postgresFullname" . }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "node-graphql-chart.postgresFullname" . }}
                  key: POSTGRES_DB
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgres.storage }}
{{- end }}